// wolox-books-vue/src/views/SignUp.vue
<template lang="pug">
  .container.column.center.middle
    .form.column.center.middle
      img.logo(src='../assets/wolox-logo.png' alt="wolox-logo")
      h2.title books
      form.content(@submit.prevent)
        .form-item
          span.name(:class="{error: $v.firstName.$error}")
            | First name
          input.input(v-model.trim="firstName")
          span.error-label(v-if="!$v.firstName.required && $v.firstName.$dirty")
            | El campo es requerido
        .form-item
          span.name(:class="{error: $v.lastName.$error}")
            | Last name
          input.input(v-model="lastName")
          span.error-label(v-if="!$v.lastName.required && $v.lastName.$dirty")
            | El campo es requerido
        .form-item
          span.name(:class="{error: $v.email.$error}")
            | Email
          input.input(v-model="$v.email.$model")
          span.error-label(v-if="!$v.email.required && $v.email.$dirty")
            | El campo es requerido
        .form-item
          span.name(:class="{error: $v.password.$error}")
            | Password
          input.input(v-model.trim="$v.password.$model")
          span.error-label(v-if="!$v.password.required && $v.password.$dirty")
            | El campo es requerido
        button.btn.primary.full-width.m-bottom-2(@click="logInfo")
          | Sign Up
      router-link.btn.secondary.full-width.m-top-2(to="")
        | Log In
</template>

<script>
import { required } from 'vuelidate/lib/validators'
import { UserService } from '../services/userService'

const userService = new UserService()

export default {
  data () {
    return {
      firstName: '',
      lastName: '',
      email: '',
      password: ''
    }
  },
  methods: {
    logInfo () {
      this.$v.$touch()

      if (!this.$v.$invalid) {
        const data =
          {
            user: {
              first_name: this.firstName,
              last_name: this.lastName,
              email: this.email,
              password: this.password,
              password_confirmation: this.password,
              locale: "en"
            }
          }
        userService.createUser(data)
          .then(res => console.log(res))
      }
    }

  },
  validations: {
    email: { required },
    password: { required },
    firstName: { required },
    lastName: { required }
  }
}
</script>

<style lang="scss" scoped>
@import '../scss/colors';

  .container {
    min-height: 100vh;
  }

  .form {
    width: 370px;
    background-color: $wild-sand;
    padding: 20px;
    border-top: 4px solid $celurean;
  }

  .logo {
    width: 100%;
    margin-bottom: 10px;
  }

  .title {
    font-size: 15px;
    letter-spacing: 4px;
    text-transform: uppercase;
    font-weight: bold;
    margin-bottom: 50px;
  }

  .content {
    width: 100%;
    border-bottom: 2px solid $alto;
  }
</style>

// wolox-books/src/app/screens/sign-up/sign-up.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

import { UserServiceService } from '../../services/user-service.service';

@Component({
  selector: 'sign-up',
  templateUrl: './sign-up.component.html',
  styleUrls: ['./sign-up.component.scss']
})
export class SignUpComponent implements OnInit {

  rForm: FormGroup;

  constructor(private fb:FormBuilder, private userService: UserServiceService) { 

    this.rForm = fb.group({
      'firstName': [],
      'lastName': [],
      'email': [],
      'password': []
    })
  }

  ngOnInit() {
  }

  signUp() {
    console.log({user: {...this.rForm.value, password_confirmation: this.rForm.value.password, locale: "en"}});
  }
}

<div class="content">
  <img class="wolox-logo" src="/assets/wolox_books_logo.png" alt="wolox-logo">
  <form class="form" [formGroup]="rForm" (ngSubmit)="signUp()">
    <label class="text">
      First name
    </label>
    <input class="input" type="text" formControlName="firstName">
    <label class="text">
      Last name
    </label>
    <input class="input" type="text" formControlName="lastName">
    <label class="text">
      Email
    </label>
    <input class="input" type="text" formControlName="email">
    <label class="text">
      Password
    </label>
    <input class="input" type="text" formControlName="password">
    <button type="submit" class="button primary-button">Sign up</button>
  </form>
  <button type="button" class="button secondary-button">Login</button>
</div>
